config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/top'
  end
  namespace :admin do
    get 'orders/show'
  end
  namespace :public do
    get 'orders/new'
    get 'orders/confirm'
    get 'orders/complete'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
    get 'items/edit'
  end
  namespace :public do
    get 'deliveries/index'
    get 'deliveries/edit'
  end
  namespace :public do
    get 'customers/show'
    get 'customers/edit'
    get 'customers/unsubscribe'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]
    root to: "homes#top"
    get 'about' => 'homes#about', as: 'about'
    get 'customers/my_page'  => 'customers#show'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    get 'orders/complete', to: 'orders#complete', as: 'complete'
    post 'orders/comfirm', to: 'orders#confirm', as: 'confirm'
    resources :orders, only: [:index, :show, :create, :new]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :customers, only: [:index, :edit, :show, :update]
  resources :orders, only: [:show, :update]
  resources :order_items, only: [:update]
  get '/' => 'homes#top'  
end
end

app/models/item.rb
class Item < ApplicationRecord
belongs_to :genre
has_many :cart_items, dependent: :destroy
has_many :order_items, dependent: :destroy

def with_tax_price
    (price * 1.1).floor
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(admin_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end
  
  def index
    @item = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(admin_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end
  
  private

  def admin_params
    params.require(:item).permit(:name, :introduction, :genre, :price, :is_active, :image, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <h2>商品編集</h2>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model:@item, url: admin_item_path, method: :patch, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.label :genre %>
          <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {include_blank: '---'} %>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class:'form-control book_title' %><p>円</p>
        </div>
        <div class="form-group">
          <%= f.label :is_active, '販売中', value: 1 %>
          <%= f.radio_button :is_active, '1' %>
          <%= f.label :is_active, '販売停止中', value: 0 %>
          <%= f.radio_button :is_active, '0' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>商品一覧</h2>
      <%=link_to "商品新規登録", new_admin_item_path %>
        <table class='table table-hover table-inverse'>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
          <% @item.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id)%></td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <% if item.is_active == true %>
              <td><p class="text-success">販売中</p></td>
            <% else %>
              <td><p class="text-muted">販売中止中</p></td>
            <% end %>
          </tr>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>商品新規登録</h2>
        <%= form_with model:@item, url: admin_items_path, method: :post do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, class: 'form-control book_body' %>
          </div>
          <div class="form-group">
            <%= f.label :genre %>
            <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {include_blank: '---'} %>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class:'form-control book_title' %><p>円</p>
          </div>
          <div class="form-group">
            <%= f.label :is_active, '販売中', value: 1 %>
            <%= f.radio_button :is_active, '1' %>
            <%= f.label :is_active, '販売停止中', value: 0 %>
            <%= f.radio_button :is_active, '0' %>
          </div>
          <div class="form-group">
            <%= f.submit class: 'btn btn-success' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container'>
  <div class='row'>
    <h2>商品詳細</h2>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto pt-5">
      <p><%= "商品名" %>　<%= @item.id %></p>
      <p><%= "商品詳細" %>　<%= @item.introduction %></p>
      <p><%= "ジャンル" %>　<%= @item.genre.name %></p>
      <p><%= "税込価格(税抜価格)" %>　<%= @item.price %></p>
      <p>
        <%= "販売ステータス" %>　
        <% if @item.is_active == true %>
          <p class="text-success">販売中</p>
        <% else %>
          <p class="text-muted">販売中止中</p></td>
        <% end %>
      </p>
      <p><%= link_to "編集する", edit_admin_item_path(@item.id) %></p>
    </div>
  </div>
</div>