config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/top'
  end
  namespace :admin do
    get 'orders/show'
  end
  namespace :public do
    get 'orders/new'
    get 'orders/confirm'
    get 'orders/complete'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
    get 'items/edit'
  end
  namespace :public do
    get 'deliveries/index'
    get 'deliveries/edit'
  end
  namespace :public do
    get 'customers/show'
    get 'customers/edit'
    get 'customers/unsubscribe'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]
    root to: "homes#top"
    get 'about' => 'homes#about', as: 'about'
    get 'customers/my_page'  => 'customers#show'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    get 'orders/complete', to: 'orders#complete', as: 'complete'
    post 'orders/comfirm', to: 'orders#confirm', as: 'confirm'
    resources :orders, only: [:index, :show, :create, :new]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :customers, only: [:index, :edit, :show, :update]
  resources :orders, only: [:show, :update]
  resources :order_items, only: [:update]
  get '/' => 'homes#top'  
end
end

app/models/order.rb
class Order < ApplicationRecord
 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: {
    waiting_for_payment: 0,
    payment_confirmation: 1,
    now_at_work: 2,
    shopping_preparation: 3,
    shopped: 4
  }
  
  has_many :order_items, dependent: :destroy
  belongs_to :customer
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_item = @order.order_items
    @total = @order_item.inject(0) {|sum, cart_item| sum + cart_item.subtotal}
  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_params)
   if @order.status == "payment_confirmation"                      #もし入金確認に更新されたら
      @order_item = @order.order_items                             #orderに紐づく商品すべてを
      @order_item.update_all(making_status:'waiting_production')   #製作待ちに変更する
   end
      redirect_back(fallback_location: admin_order_path)
  end
  
  private

  def order_params
    params.require(:order).permit(:status, :order_item)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<div>
 <p>購入者</p><p><%= link_to @order.name, admin_customer_path(@order.customer) %></p>
 <p>注文日</p><p><%= @order.created_at%></p>
 <p>配送先</p><p>〒<%= @order.post_code%> <%= @order.address%></p>
 <p>支払方法</p><p><%= @order.payment_method_i18n %></p>
</div>

<h2>ステータス編集フォーム</h2>
<div>
 <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
  <%= f.select :status, Order.statuses_i18n.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>
  <%= f.submit "更新", class: 'btn btn-success' %>
 <% end %>
</div>

<h2>注文詳細</h2>
<table>
 <tr>
  <th>商品名</th>
  <th>単価（税込）</th>
  <th>数量</th>
  <th>小計</th>
  <th>製作ステータス</th>
  <th></th>
 </tr>
 
 <% @order_item.each do |order_item| %>
  <tr>
   <td><%= order_item.item.name %></td>
   <td><%= order_item.item.with_tax_price %></td>
   <td><%= order_item.amount %></td>
   <td><%= order_item.subtotal %></td>
   <%= form_with model: order_item, url: admin_order_item_path(order_item.id), method: :patch do |f| %>
    <td><%= f.select :making_status, OrderItem.making_statuses_i18n.keys.map { |k| [I18n.t("enums.order_item.making_status.#{k}"), k] } %></td>
    <td><%= f.submit "更新" %></td>
   <% end %> 
   </td>
  </tr>
 <% end %>
</table>

<table>
 <tr>
  <td>送料</td>
  <td><%= @order.postage %></td>
 </tr>
 
 <tr>
  <td>合計金額</td>
  <td><%= @total %></td>
 </tr> 
 
 <tr>
  <td>請求金額</td>
  <td><%= @order.total_payment = @order.postage + @total %></td>
 </tr> 
</table>