config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/top'
  end
  namespace :admin do
    get 'orders/show'
  end
  namespace :public do
    get 'orders/new'
    get 'orders/confirm'
    get 'orders/complete'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
    get 'items/edit'
  end
  namespace :public do
    get 'deliveries/index'
    get 'deliveries/edit'
  end
  namespace :public do
    get 'customers/show'
    get 'customers/edit'
    get 'customers/unsubscribe'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]
    root to: "homes#top"
    get 'about' => 'homes#about', as: 'about'
    get 'customers/my_page'  => 'customers#show'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    get 'orders/complete', to: 'orders#complete', as: 'complete'
    post 'orders/comfirm', to: 'orders#confirm', as: 'confirm'
    resources :orders, only: [:index, :show, :create, :new]
  end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :customers, only: [:index, :edit, :show, :update]
  resources :orders, only: [:show, :update]
  resources :order_items, only: [:update]
  get '/' => 'homes#top'  
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
end

app/models/delivery.rb
class Delivery < ApplicationRecord
 belongs_to :customer
 def address_display
  '〒' + post_code + ' ' + address + ' ' + name
 end
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
belongs_to :genre
has_many :cart_items, dependent: :destroy
has_many :order_items, dependent: :destroy

def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord
 enum payment_method: { credit_card: 0, transfer: 1 }
 enum status: {
    waiting_for_payment: 0,
    payment_confirmation: 1,
    now_at_work: 2,
    shopping_preparation: 3,
    shopped: 4
  }
  
  has_many :order_items, dependent: :destroy
  belongs_to :customer
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status: {
    not_created: 0,
    waiting_production: 1,
    in_production: 2,
    completed: 3
  }
  
  belongs_to :order
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres=Genre.all
      render :index
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      @genres=Genre.all
      render :index
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(admin_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end
  
  def index
    @item = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(admin_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end
  
  private

  def admin_params
    params.require(:item).permit(:name, :introduction, :genre, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ￥priceで表示する
  def to_total_currency(price)
    number_to_currency(price, unit:'￥', strip_insignificant_zeros: true)
  end
  
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
        <% if customer_signed_in? %> 
          <li class="mr-3">
            <%= link_to "マイページ", customers_my_page_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "商品一覧", items_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "カート", cart_items_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: 'nav-link text-light' %>
          </li>
        
        <% elsif admin_signed_in? %> 
          <li class="mr-3">
            <%= link_to "商品一覧", admin_items_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "会員一覧", admin_customers_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%#= link_to "注文履歴一覧", admin_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "ジャンル一覧", admin_genres_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'nav-link text-light' %>
          </li>
        <% else %>
          <li class="mr-3">
            <%= link_to "About", about_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%#= link_to "商品一覧", items_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "新規登録", new_customer_registration_path,class: 'nav-link text-light' %>
          </li>
          <li class="mr-3">
            <%= link_to "ログイン", new_customer_session_path,class: 'nav-link text-light' %>
          </li>
        <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>N</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= render 'layouts/header' %>
    </main>
    <%= yield %>
  </body>
</html>